config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    root to: "feature_request#index"
    get 'staffs/staff_new' => 'staffs#staff_new', :as => 'staff_new'
    post 'staffs/registration_staff' => 'staffs#registration_staff', :as => 'registration_staff'
    get 'staffs/sign_out' => 'staffs#logout', :as => 'staff_sign_out'

    get 'staffs/staff_list' => 'staffs#staff_list'
    get 'staffs/staff_edit/' => 'staffs#staff_edit'
    put 'staffs/update_staff' => 'staffs#update_staff', :via => [:put, :patch]
    patch 'staffs/update_staff' => 'staffs#update_staff', :via => [:put, :patch]
    delete 'staffs/destroy/' => 'staffs#destroy'

  end

  resources :clients
  get 'clients/register' => 'clients#register'
  resources :feature_request
  get '/deactive_request' => 'feature_request#deactive_request', :as => 'deactive_request'
  get '/activate_request' => 'feature_request#activate_request', :as => 'activate_request'
  post 'feature_request/complete_request' => 'feature_request#complete_request'
  resources :product_area

end

app/models/feature_request.rb
class FeatureRequest < ActiveRecord::Base
end

app/controllers/feature_request_controller.rb
class FeatureRequestController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    if user_signed_in?
      if current_user.is_staff == 0
        @feature = FeatureRequest.select("feature_requests.*, clients.title AS client_title, product_areas.product_area, users.first_name").joins("INNER JOIN clients ON feature_requests.client_id=clients.id").joins("INNER JOIN product_areas ON feature_requests.product_id=product_areas.id").joins("INNER JOIN users on users.id=feature_requests.user_id")
      else
        @feature = FeatureRequest.select("feature_requests.*, clients.title AS client_title, product_areas.product_area, users.first_name").joins("INNER JOIN clients ON feature_requests.client_id=clients.id").joins("INNER JOIN product_areas ON feature_requests.product_id=product_areas.id").joins("INNER JOIN users on users.id=feature_requests.user_id").where("feature_requests.user_id = #{current_user.id}")
      end
    else
      redirect_to new_user_session_path
    end
    # raise @feature.inspect
  end

  def new
    @feature = FeatureRequest.new
  end

  def create
    request_params[:title] = params[:feature_request][:title].strip()
    request_params[:description] = params[:feature_request][:description].strip()
    request_params[:client_id] = params[:feature_request][:client_id]
    request_params[:client_priority] = params[:feature_request][:client_priority]
    request_params[:target_date] = params[:feature_request][:target_date]
    request_params[:ticket_url] = params[:feature_request][:ticket_url].strip()
    request_params[:product_id] = params[:feature_request][:product_id]
    @user_id = current_user.id
    if params[:feature_request][:client_priority].to_i == 1
      @feature_req = FeatureRequest.where(client_id: params[:feature_request][:client_id]).where("status=0")
      if @feature_req.present?
        if @feature_req.map(&:client_priority).include? 1
          @feature_req.each do |req|
            req.client_priority = req.client_priority + 1
            req.save
          end
          @feature = FeatureRequest.new(request_params)
          if @feature.save
            @feature.update_attribute(:user_id, @user_id)
            flash[:notice] = "Successfully created"
            redirect_to feature_request_index_path
          else
            render :new
          end
        else
          @feature = FeatureRequest.new(request_params)
          if @feature.save
            @feature.update_attribute(:user_id, @user_id)
            flash[:notice] = "Successfully created"
            redirect_to feature_request_index_path
          else
            render :new
          end
        end
      else
        @feature = FeatureRequest.new(request_params)
        if @feature.save
          @feature.update_attribute(:user_id, @user_id)
          flash[:notice] = "Successfully created"
          redirect_to feature_request_index_path
        else
          render :new
        end
      end
    else
      @feature = FeatureRequest.new(request_params)
      if @feature.save
        @feature.update_attribute(:user_id, @user_id)
        flash[:notice] = "Successfully created"
        redirect_to feature_request_index_path
      else
        render :new
      end
    end

  end

  def edit
    @feature = FeatureRequest.find(params[:id])
  end

  def update
    request_params[:title] = params[:feature_request][:title].strip()
    request_params[:description] = params[:feature_request][:description].strip()
    request_params[:client_id] = params[:feature_request][:client_id]
    request_params[:client_priority] = params[:feature_request][:client_priority]
    request_params[:target_date] = params[:feature_request][:target_date]
    request_params[:ticket_url] = params[:feature_request][:ticket_url].strip()
    request_params[:product_id] = params[:feature_request][:product_id]

    @feature = FeatureRequest.find(params[:id])
    if @feature.update_attributes(request_params)
      flash[:notice] = "Successfully updated"
      redirect_to feature_request_index_path
    else
      render :edit
    end
  end

  def destroy
    @feature = FeatureRequest.find(params[:id])

    if @feature.present?
      @feature.destroy
      flash[:notice] = "Successfully deleted"
      redirect_to feature_request_index_path
    end
  end

  def deactive_request
    @feature = FeatureRequest.find(params[:id])
    if @feature.update_attribute(:status, 1)
      @feature_req = FeatureRequest.where(client_id: @feature.client_id).where("status=0")
      # raise @feature_req.inspect
      if @feature_req.present?
        @feature_req.each do |req|
          req.client_priority = req.client_priority - 1
          req.save
        end
      flash[:notice] = "Successfully updated"
      redirect_to feature_request_index_path
      end
    else
      render :edit
    end
  end

  def activate_request
    @feature = FeatureRequest.find(params[:id])
    if @feature.update_attribute(:status, 1)
      flash[:notice] = "Successfully updated"
      redirect_to feature_request_index_path
    else
      render :edit
    end
  end

  def complete_request
    if current_user.is_staff == 0
      @feature = FeatureRequest.select("feature_requests.*, clients.title AS client_title, product_areas.product_area, users.first_name").joins("INNER JOIN clients ON feature_requests.client_id=clients.id").joins("INNER JOIN product_areas ON feature_requests.product_id=product_areas.id").joins("INNER JOIN users on users.id=feature_requests.user_id").where("feature_requests.status=1")
    else
      if params[:status] == 'complete'
        @feature = FeatureRequest.select("feature_requests.*, clients.title AS client_title, product_areas.product_area, users.first_name").joins("INNER JOIN clients ON feature_requests.client_id=clients.id").joins("INNER JOIN product_areas ON feature_requests.product_id=product_areas.id").joins("INNER JOIN users on users.id=feature_requests.user_id").where("feature_requests.status=1")
      end
    end
  else
    redirect_to new_user_session_path
  end

  private
  def request_params
    params.require(:feature_request).permit(:title, :description, :client_id, :client_priority, :target_date, :ticket_url, :product_id)
  end
end

app/helpers/feature_request_helper.rb
module FeatureRequestHelper
end

app/views/feature_request/_form.html.erb
<%= form_for @feature, url: feature_request_index_path do |f| %>


    <div class="form-group">

      <%= f.label :title %>
      <%= f.text_field :title, placeholder: '', class: 'form-control', :required => 'required' %>


    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>

    <div class="form-group">
      <%= f.label :client_id %><br>
      <%= f.collection_select(:client_id, Client.all, :id, :title, :prompt => true) %>
    </div>
    <div class="form-group">
      <%= f.label :client_priority %>
      <%= f.text_field :client_priority, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :target_date %>
      <%= f.date_field :target_date, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :ticket_url %>
      <%= f.text_field :ticket_url, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>

    <div class="form-group">
      <%= f.label :Product_area %><br>
      <%= f.collection_select(:product_id, ProductArea.all, :id, :product_area, :prompt => true) %>
    </div>

    <%= f.submit f.object.new_record? ? 'Save' : 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/feature_request/compelete_request.html.erb
<div>
  <h1>
    <span>Request</span><br>
    <%= link_to "Completed", complete_request_path, class: '' %>
  </h1>
  <% if current_user.is_staff == 1 %>
      <%= link_to "Add Request", new_feature_request_path, class: 'add_new btn btn-success' %>
  <% end %>
  <% if @feature.blank? %>
      <p style="text-align: center; font-size: 18px;">No record found.</p>
  <% else %>


      <p></p>
      <hr>

      <table class="table table-bordered" border="1" width="100%" style="border-collapse: collapse;">
        <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Client</th>
          <th>Client Priority</th>
          <th>Target Date</th>
          <th>Ticket URL</th>
          <th>Product Area</th>
          <th>Staff Name</th>
          <th>Status</th>
          <th>Edit</th>
          <th>Delete</th>

        </tr>
        </thead>
        <tbody>

        <%- @feature.each do |c| %>
            <tr>
              <td><%= c.title %></td>
              <td><%= c.description %></td>
              <td><%= c.client_title %></td>
              <td><%= c.client_priority %></td>
              <td><%= c.target_date %></td>
              <td><%= c.ticket_url %></td>
              <td><%= c.product_area %></td>
              <td><%= c.first_name %></td>
              <% if current_user.is_staff == 1 %>
                  <% if c.status == 0 %>
                      <td><%= link_to "Begin", deactive_request_path(:id => c.id), data: {confirm: 'Are you sure! you want to activate this request?'}, class: 'btn btn-success' %></td>

                  <% else %>
                      <td><%= link_to "Completed" %></td>
                  <% end %>
              <% else %>
                  <td>
                    <% if c.status == 0 %>
                        <span style="color:green;"> Pending </span>
                    <% else %>
                        <span style="color:red;">Completed</span>
                        </td>
                    <% end %>
              <% end %>
              <td>
                <%= link_to "Edit", edit_feature_request_path(c.id), class: 'btn btn-success' %></td>
              <td>
                <%= link_to "Delete", c, method: :delete, data: {confirm: 'Are you sure you want to delete this request?'}, class: 'btn btn-danger' %>
              </td>
        <% end %>
        </tr>
        </tbody>
      </table>
  <% end %>
</div>
</div>
</div>

app/views/feature_request/edit.html.erb
<%= form_for @feature, url: feature_request_path do |f| %>


    <div class="form-group">

      <%= f.label :title %>
      <%= f.text_field :title, placeholder: '', class: 'form-control', :required => 'required' %>


    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :client_id %><br>
      <%= f.collection_select(:client_id, Client.all, :id, :title, :prompt => true) %>
    </div>
    <div class="form-group">
      <%= f.label :client_priority %>
      <%= f.text_field :client_priority, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :target_date %>
      <%= f.date_field :target_date, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :ticket_url %>
      <%= f.text_field :ticket_url, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>

    <div class="form-group">
      <%= f.label :Product_area %><br>
      <%= f.collection_select(:product_id, ProductArea.all, :id, :product_area, :prompt => true) %>
    </div>

    <%= f.submit f.object.new_record? ? 'Save' : 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/feature_request/index.html.erb
<div>
  <h1>
    <span>Request</span><br>

  </h1>
  <% if current_user.is_staff == 1 %>
      <%= link_to "Add Request", new_feature_request_path, class: 'add_new btn btn-success' %>
  <% end %>
  <% if @feature.blank? %>
      <p style="text-align: center; font-size: 18px;">No record found.</p>
  <% else %>


      <p></p>
      <hr>

      <table class="table table-bordered" border="1" width="100%" style="border-collapse: collapse;">
        <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Client</th>
          <th>Client Priority</th>
          <th>Target Date</th>
          <th>Ticket URL</th>
          <th>Product Area</th>
          <th>Staff Name</th>
          <th>Status</th>
          <th>Edit</th>
          <th>Delete</th>

        </tr>
        </thead>
        <tbody>

        <%- @feature.each do |c| %>
            <tr>
              <td><%= c.title %></td>
              <td><%= c.description %></td>
              <td><%= c.client_title %></td>
              <td><%= c.client_priority %></td>
              <td><%= c.target_date %></td>
              <td><%= c.ticket_url %></td>
              <td><%= c.product_area %></td>
              <td><%= c.first_name %></td>
              <% if current_user.is_staff == 1 %>
                  <% if c.status == 0 %>
                      <td><%= link_to "Begin", deactive_request_path(:id => c.id), data: {confirm: 'Are you sure! you want to activate this request?'}, class: 'btn btn-success' %></td>

                  <% else %>
                      <td><%= link_to "Completed" %></td>
                  <% end %>
              <% else %>
                  <td>
                    <% if c.status == 0 %>
                        <span style="color:green;"> Pending </span>
                    <% else %>
                        <span style="color:red;">Completed</span>
                        </td>
                    <% end %>
              <% end %>
              <td>
                <%= link_to "Edit", edit_feature_request_path(c.id), class: 'btn btn-success' %></td>
              <td>
                <%= link_to "Delete", c, method: :delete, data: {confirm: 'Are you sure you want to delete this request?'}, class: 'btn btn-danger' %>
              </td>
        <% end %>
        </tr>
        </tbody>
      </table>
  <% end %>
</div>
</div>
</div>

app/views/feature_request/new.html.erb
<h1 style="margin-left:2%; color: black"><b>New Request</b></h1>
<hr>
<%= render "form" %>
</div>
</div>