config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    root to: "feature_request#index"
    get 'staffs/staff_new' => 'staffs#staff_new', :as => 'staff_new'
    post 'staffs/registration_staff' => 'staffs#registration_staff', :as => 'registration_staff'
    get 'staffs/sign_out' => 'staffs#logout', :as => 'staff_sign_out'

    get 'staffs/staff_list' => 'staffs#staff_list'
    get 'staffs/staff_edit/' => 'staffs#staff_edit'
    put 'staffs/update_staff' => 'staffs#update_staff', :via => [:put, :patch]
    patch 'staffs/update_staff' => 'staffs#update_staff', :via => [:put, :patch]
    delete 'staffs/destroy/' => 'staffs#destroy'

  end

  resources :clients
  get 'clients/register' => 'clients#register'
  resources :feature_request
  get '/deactive_request' => 'feature_request#deactive_request', :as => 'deactive_request'
  get '/activate_request' => 'feature_request#activate_request', :as => 'activate_request'
  post 'feature_request/complete_request' => 'feature_request#complete_request'
  resources :product_area

end

app/models/product_area.rb
class ProductArea < ActiveRecord::Base
end

app/controllers/product_area_controller.rb
class ProductAreaController < ApplicationController
  def index
    @product = ProductArea.all()
  end

  def new
    @product = ProductArea.new()
  end

  def create
    req_params[:product_area] = req_params[:product_area].strip()
    req_params[:product_description] = req_params[:product_description].strip()

    @product = ProductArea.new(req_params)
    if @product.save
      flash[:notice] = "Successfully created"
      redirect_to product_area_index_path
    else
      render :new
    end
  end

  def edit
    @product = ProductArea.find(params[:id])
  end

  def update
    req_params[:product_area] = req_params[:product_area].strip()
    req_params[:product_description] = req_params[:product_description].strip()

    @product = ProductArea.find(params[:id])
    if @product.update_attributes(req_params)
      flash[:notice] = "Successfully updated"
      redirect_to product_area_index_path
    else
      render :edit
    end
  end

  def destroy
    @product = ProductArea.find(params[:id])

    if @product.present?
      @product.destroy
      flash[:notice] = "Successfully deleted"
      redirect_to product_area_index_path
    end
  end

  private
  def req_params
    params.require(:product_area).permit(:product_area, :product_description)
  end
end

app/helpers/product_area_helper.rb
module ProductAreaHelper
end

app/views/product_area/_form.html.erb
<%= form_for @product, url: product_area_index_path do |f| %>


    <div class="form-group">

      <%= f.label :product_area %>
      <%= f.text_field :product_area, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>

    <div class="form-group">
      <%= f.label :product_description %>
      <%= f.text_field :product_description, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <%= f.submit f.object.new_record? ? 'Save' : 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/product_area/edit.html.erb
<%= form_for @product, url: product_area_path do |f| %>


    <div class="form-group">

      <%= f.label :product_area %>
      <%= f.text_field :product_area, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>

    <div class="form-group">
      <%= f.label :product_description %>
      <%= f.text_field :product_description, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <%= f.submit f.object.new_record? ? 'Save' : 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/product_area/index.html.erb
<div>
  <h1>
    <span>Product Area</span>
  </h1>
  <%= link_to "Add Product", new_product_area_path, class: 'add_new btn btn-success' %>
  <% if @product.blank? %>
      <p style="text-align: center; font-size: 18px;">No product found.</p>
  <% else %>

      <p></p>
      <table class="table table-bordered" border="1" width="100%" style="border-collapse: collapse;">
        <thead>
        <tr>
          <th>Product Area</th>
          <th>Product Description</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        <%- @product.each do |c| %>
            <tr>
              <td><%= c.product_area %></td>
              <td><%= c.product_description %></td>
              <td>
                <%= link_to "Edit", edit_product_area_path(c.id), class: 'btn btn-success' %></td>
              <td>
                <%= link_to "Delete", c, method: :delete, data: {confirm: 'Are you sure you want to delete this product area?'}, class: 'btn btn-danger' %>
              </td>
        <% end %>
        </tr>
        </tbody>
      </table>
  <% end %>
</div>
</div>
</div>

app/views/product_area/new.html.erb
<h1 style="margin-left:2%; color: black"><b>New Product Area</b></h1>
<hr>
<%= render "form" %>
</div>
</div>