config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    root to: "feature_request#index"
    get 'staffs/staff_new' => 'staffs#staff_new', :as => 'staff_new'
    post 'staffs/registration_staff' => 'staffs#registration_staff', :as => 'registration_staff'
    get 'staffs/sign_out' => 'staffs#logout', :as => 'staff_sign_out'

    get 'staffs/staff_list' => 'staffs#staff_list'
    get 'staffs/staff_edit/' => 'staffs#staff_edit'
    put 'staffs/update_staff' => 'staffs#update_staff', :via => [:put, :patch]
    patch 'staffs/update_staff' => 'staffs#update_staff', :via => [:put, :patch]
    delete 'staffs/destroy/' => 'staffs#destroy'

  end

  resources :clients
  get 'clients/register' => 'clients#register'
  resources :feature_request
  get '/deactive_request' => 'feature_request#deactive_request', :as => 'deactive_request'
  get '/activate_request' => 'feature_request#activate_request', :as => 'activate_request'
  post 'feature_request/complete_request' => 'feature_request#complete_request'
  resources :product_area

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all()
  end


  def show
    @client = Client.all()
  end

  def new
    @client = Client.new
  end

  def create
    client_params[:title] = client_params[:title].strip()
    client_params[:description] = client_params[:description].strip()
    client_params[:first_name] = client_params[:first_name].strip()
    client_params[:last_name] = client_params[:last_name].strip()
    client_params[:email] = client_params[:email].strip()

    @client = Client.new(client_params)
    if @client.save
      flash[:notice] = "Successfully created"
      redirect_to clients_path
    else
      render :new
    end
  end


  def edit
    @clients = Client.find(params[:id])
  end

  def update
    client_params[:title] = client_params[:title].strip()
    client_params[:description] = client_params[:description].strip()
    client_params[:first_name] = client_params[:first_name].strip()
    client_params[:last_name] = client_params[:last_name].strip()
    client_params[:email] = client_params[:email].strip()

    @client = Client.find(params[:id])
    if @client.update_attributes(client_params)
      flash[:notice] = "Successfully updated"
      redirect_to client_path
    else
      render :edit
    end
  end

  def destroy
    @client = Client.find(params[:id])

    if @client.present?
      @client.destroy
      flash[:notice] = "Successfully deleted"
      redirect_to client_path
    end
  end

  private
  def client_params
    params.require(:client).permit(:first_name, :last_name, :email, :title, :description)
  end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/_form.html.erb
<%= form_for @client, url: clients_path do |f| %>

    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>

    <%= f.submit f.object.new_record? ? 'Save' : 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/clients/edit.html.erb
<%= form_for @clients, url: client_path do |f| %>

    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>
    <div class="form-group">

      <%= f.label :title %>
      <%= f.text_field :title, placeholder: '', class: 'form-control', :required => 'required' %>


    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: '', class: 'form-control', :required => 'required' %>
    </div>

    <%= f.submit f.object.new_record? ? 'Update' : 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/clients/index.html.erb
<div>

  <h1>Clients
  </h1>

  <% if current_user.present? and current_user.is_admin != nil %>
      <% if @clients.blank? %>
      <p style="text-align: center; font-size: 18px;">No record found.</p>
  <% else %>

      <p></p>
      <hr>
      <table class="table table-bordered" border="" width="100%" style="border-collapse: collapse;">
        <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Client Title</th>
          <th>Description</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        <%- @clients.each do |c| %>
            <tr>
              <td><%= c.first_name %></td>
              <td><%= c.last_name %></td>
              <td><%= c.email %></td>
              <td><%= c.title %></td>
              <td><%= c.description %></td>
              <td>
                <%= link_to "Edit", edit_client_path(c.id), class: 'btn btn-success' %></td>
              <td>
                <%= link_to "Delete", c, method: :delete, data: {confirm: 'Are you sure you want to delete this client?'}, class: 'btn btn-danger' %>
              </td>
        <% end %>
        </tr>
        </tbody>
      </table>
  <% end %>
  <% else %>
      <%= link_to "Register", new_client_path, class: 'add_new btn btn-success' %>
  <% end %>
</div>
</div>
</div>

app/views/clients/new.html.erb
<h1 style="margin-left:2%; color: black"><b>New Client</b></h1>
<hr>
<%= render "form" %>

app/views/clients/show.html.erb
<div>
  <h1>
    <span>Client</span>

  </h1>

  <%= link_to "Add New Client", new_client_path, class: 'add_new' %>

  <p></p>
  <hr>

  <table class="table table-bordered" border="1" width="100%" style="border-collapse: collapse;">
    <thead>
    <tr>
      <th>Client Title</th>
      <th>Description</th>
      <th>Edit</th>
      <th>Delete</th>

    </tr>
    </thead>
    <tbody>

    <%- @client.each do |c| %>
        <tr>
          <td><%= c.title %></td>
          <td><%= c.description %></td>
          <td>
            <%= link_to "Edit", edit_client_path(c.id), class: 'btn btn-success ' %></td>
          <td>
            <%= link_to "Delete", c, method: :delete, data: {confirm: 'Are you sure you want to delete this client?'}, class: 'btn btn-danger' %>
          </td>
    <% end %>
    </tr>
    </tbody>
  </table>
</div>
</div>
</div>