config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    root to: "feature_request#index"
    get 'staffs/staff_new' => 'staffs#staff_new', :as => 'staff_new'
    post 'staffs/registration_staff' => 'staffs#registration_staff', :as => 'registration_staff'
    get 'staffs/sign_out' => 'staffs#logout', :as => 'staff_sign_out'

    get 'staffs/staff_list' => 'staffs#staff_list'
    get 'staffs/staff_edit/' => 'staffs#staff_edit'
    put 'staffs/update_staff' => 'staffs#update_staff', :via => [:put, :patch]
    patch 'staffs/update_staff' => 'staffs#update_staff', :via => [:put, :patch]
    delete 'staffs/destroy/' => 'staffs#destroy'

  end

  resources :clients
  get 'clients/register' => 'clients#register'
  resources :feature_request
  get '/deactive_request' => 'feature_request#deactive_request', :as => 'deactive_request'
  get '/activate_request' => 'feature_request#activate_request', :as => 'activate_request'
  post 'feature_request/complete_request' => 'feature_request#complete_request'
  resources :product_area

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EngineeringProject</title>
  <!--<script src="/assetsapplication-5ae51116e00f948ea48fd06f9f276e0d135ff08c37b4b87dc155f306fca205be.js" data-turbolinks-track="true"></script>-->
  <!--<link media="all" rel="stylesheet" href="/assetsapplication-5fa5430c470f610c05669af9e7191246e1371fe0fcd4ad2d5c39adde0a4dc788.css" data-turbolinks-track="true">-->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <p></p>
  <% if user_signed_in? %>
      <div id="menu">
        <ul>
          <li><%= link_to "Request", feature_request_index_path, method: :get %></li>
          <li><%= link_to "Staff", staffs_staff_list_path, method: :get %></li>
          <li><%= link_to "Product Area", product_area_index_path, method: :get %></li>
          <li><%= link_to "Client", clients_path, method: :get %></li>
          <li><%= link_to "Logout", staff_sign_out_path(id: current_user.id), method: :get %></li>
        </ul>
      </div>
  <% end %>
  <p class="notice"><%= notice %></p>

  <p class="alert"><%= alert %></p>
  <%= yield %>

</div>
</body>
</html>
<script>

    $(".notice").fadeOut(8000);
    $(document).ready(function () {
        $('#menu a').each(function (index) {
            if (this.href.trim() == window.location)
                $(this).addClass("active");
        });
    });

</script>
<style>
    .active {
        background-color: #d9534f;
    }

    .login {
        margin-left: 35%;
    }

    #user_email {
        width: 30%;
        padding: 3px;
    }

    #user_password {
        width: 30%;
        padding: 3px;
    }

    #user_password_confirmation {
        width: 30%;
        padding: 3px;
    }

    #menu {
        width: auto;
        height: 35px;
        font-size: 16px;
        font-family: Tahoma, Geneva, sans-serif;
        font-weight: bold;
        text-align: center;
        /*text-shadow: 3px 2px 3px #333333;*/
        background-color: #5cb85c;
        border-radius: 8px;
    }

    #menu ul {
        height: auto;
        padding: 7px 0px;
        margin: 0px;
    }

    #menu li {
        display: inline;
        padding: 20px;
    }

    #menu a {
        text-decoration: none;
        color: white;
        padding: 8px 8px 8px 8px;
    }

    #menu li {
        display: inline;
        padding: 20px;
    }

    #menu a {
        text-decoration: none;
        color: white;
        padding: 8px 8px 8px 8px;
    }

    ul {
        margin-left: -45% !important;
    }

    .add_new {
        float: right;
    }

    .add_new_cls {
        float: right;
    }

    #feature_request_client_id {
        width: 50%;
        height: 30px;
        border: 0.5px solid black;
    }

    #feature_request_product_id {
        width: 50%;
        height: 30px;
        border: 0.5px solid black;
    }

    #user_name {
        width: 30%;
        height: 30px;
    }

    #user_first_name {
        width: 30%;
        height: 30px;
    }

    #user_last_name {
        width: 30%;
        height: 30px;
    }

    #user_joining_date {
        width: 30%;
        height: 30px;
    }
</style>